name: CI workflow

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_testing.yml@develop

  deploy_develop_docs:
    name: Deploy development docs
    needs: tests
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_site.yml@develop
    with:
      branch: develop
      host: docs.bernardomg.com
    secrets:
      DEPLOY_DOCS_SITE: ${{ secrets.DEPLOY_DOCS_DEVELOP_SITE }}
      DEPLOY_DOCS_USER: ${{ secrets.DEPLOY_DOCS_DEVELOP_USER }}
      DEPLOY_DOCS_PASSWORD: ${{ secrets.DEPLOY_DOCS_DEVELOP_PASSWORD }}

  deploy_docs:
    name: Deploy docs
    needs: tests
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_site.yml@develop
    with:
      branch: master
      host: docs.bernardomg.com
    secrets:
      DEPLOY_DOCS_SITE: ${{ secrets.DEPLOY_DOCS_SITE }}
      DEPLOY_DOCS_USER: ${{ secrets.DEPLOY_DOCS_USER }}
      DEPLOY_DOCS_PASSWORD: ${{ secrets.DEPLOY_DOCS_PASSWORD }}