name: CI workflow

on: [push, pull_request]

jobs:
  tests:
    name: Run tests
    strategy:
      matrix:
        jdk: [ 11, 16 ]
    uses: ./testing.yml

  deploy_docs:
    name: Deploy docs
    needs: tests
    uses: ./deploy_docs.yml