name: CI workflow

on: [push, pull_request]

jobs:
  tests:
    name: Run tests
    uses: Bernardo-MG/dice-notation-java/.github/workflows/testing.yml@reuse_workflow

  deploy_docs:
    name: Deploy docs
    needs: tests
    uses: Bernardo-MG/dice-notation-java/.github/workflows/deploy_docs.yml@reuse_workflow