name: Artifact deployment

on:
  release:
    types: [created]

jobs:
  github:
    name: Github deployment
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_github.yml@develop
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ossrh:
    name: OSSRH deployment
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_ossrh.yml@develop
    secrets:
      USERNAME: ${{ secrets.OSSRH_USERNAME }}
      PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}