name: Artifact deployment

on:
  release:
    types: [created]

jobs:
  github:
    name: Github
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_github.yml@v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  ossrh:
    name: Deploy OSSRH

    environment: deployment_ossrh
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2.1.0
      with:
        java-version: 11
        distribution: 'adopt'
        cache: 'maven'
        server-id: deployment_ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
    - name: Deploy
      run: mvn deploy -B -P deployment-ossrh -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}