name: Artifact deployment

on:
  release:
    types: [created]

jobs:
  github:
    name: Github
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_github.yml@v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  ossrh:
    name: OSSRH
    uses: Bernardo-MG/github-workflow/.github/workflows/maven_deploy_signed.yml@v1
    secrets:
      USERNAME: ${{ secrets.OSSRH_USERNAME }}
      PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}