name: Doc deployment

on:
  push:
    branches:
    - master
    - develop

jobs:
  deploy_develop_docs:
    name: Deploy docs for develop
    environment: deployment_site
    concurrency:
      group: deploy-site-${{ github.ref }}
      cancel-in-progress: true
    if: ${{ github.ref == format('refs/heads/{0}', 'develop') }}
    runs-on: ubuntu-latest

    steps:
    - name: Deploy site
      uses: bernardo-mg/maven-site-deployment-action@develop
      with:
        host: docs.bernardomg.com
        url: ${{ secrets.url }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        jdk: 17

  deploy_master_docs:
    name: Deploy docs for master
    environment: deployment_site
    concurrency:
      group: deploy-site-${{ github.ref }}
      cancel-in-progress: true
    if: ${{ github.ref == format('refs/heads/{0}', 'master') }}
    runs-on: ubuntu-latest

    steps:
    - name: Deploy site
      uses: bernardo-mg/maven-site-deployment-action@develop
      with:
        host: docs.bernardomg.com
        url: ${{ secrets.url }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        jdk: 17
