name: Testing and validation

on:
  workflow_call:
    inputs:
      jdk:
        description: 'JDK version to use on the tests'
        required: true
        type: string

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2.4.0
    - name: Set up JDK ${{ inputs.jdk }}
      uses: actions/setup-java@v2.5.0
      with:
        java-version: ${{ inputs.jdk }}
        distribution: 'adopt'
        cache: 'maven'
    - name: Run unit tests
      run: mvn clean test

  integration_test:
    name: Integration tests
    needs: unit_test
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2.4.0
    - name: Set up JDK ${{ inputs.jdk }}
      uses: actions/setup-java@v2.5.0
      with:
        java-version: ${{ inputs.jdk }}
        distribution: 'adopt'
        cache: 'maven'
    - name: Run up to integration tests
      run: mvn clean verify
