name: Testing and validation

on:
  workflow_call

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11, 16 ]

    steps:
    - name: Check-out
      uses: actions/checkout@v2.4.0
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v2.5.0
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
        cache: 'maven'
    - name: Run unit tests
      run: mvn clean test
    - name: Save unit test reports
      uses: actions/upload-artifact@v2
      with:
        name: unit_test_reports
        path: target/surefire-reports

  integration_test:
    name: Integration tests
    needs: unit_test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 11, 16 ]

    steps:
    - name: Check-out
      uses: actions/checkout@v2.4.0
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v2.5.0
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
        cache: 'maven'
    - name: Run up to integration tests
      run: mvn clean verify
    - name: Save integration test reports
      uses: actions/upload-artifact@v2
      with:
        name: integration_test_reports
        path: target/failsafe-reports
    - name: Save coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage_test_reports
        path: target/jacoco
